### PR TITLE
fix cast class exception

### PR DESCRIPTION
**Pull request by robertbor**
solve the problem with reading the message content. There was a linebreak problem by reading message content

change version to 1.0.15

### CODE REVIEW

**Comment by kapilag** [comment]
Please check the previous pull request by georgekankava , he has made some changes based on sonar build.
Also i dont think so we need to change version for every commit, its really hard to keep track of the current version.

Best approach would be to work with one version atleast for couple of issues fixed or we should target one version to accomodate multiple features and then add them in release notes to keep track.

**Comment by lukas-abegg** [comment]
I'm with Robert. I don't see any conflicts directly in their coding. Their just editing the same class. The problem with the pull request of @georgekankava is that he has to solve his problem in the code checks. So in this case I think, first come first served!

Regarding the version change, I think we should further use the revision numbers for bug fixing. But I think we could think about doing minor changes depending on issue summaries. 

@robertbor please solve problems with text/plain emails. Afterwards you're getting my approval.

**Comment by kapilag** [comment]
Yes there are no merge conflicts but Travis is failing . his pull request
is before this pull request (absolutely first come first serve)

Reason for failing Travis is omelet-parent version which @georgekankava
should have fixed but I don't blame him as this issue was already present
the time he forked the repo and I believe still present in the developer
branch

Regarding version . New version for every bug fix ??
Could you please explain the reason for this

My reason for not having new version is if we have 41 bugs then we will be
having 41 releases.
Fix version helps in tracking issues but the same  functionality can be
achieved by proper commit message. What we can do is create enhancements as
one of the label in issue.

Now if we have one card like "refactor email functionality" and the commit
messages for that card should have issue number for tracking and reverting

But again this is my opinion. Happy to have a discussion

Thanks
Kapil Aggarwal

**Comment by robertbor** [comment]
Regarding versions. I think it is a good idea to have small and quick changes when a bug is there. At the moment the function to get mail is buggy and not working fine. So if one will use the function i think it is a good idea so fix the problem as soon as possible.

When we will have new features yes of course it can make sense to wait a few changes and present more then one new feature.

**Comment by lukas-abegg** [comment]
Because its a bugfix I think we should approve this.

As I've seen in the pull request from @georgekankava there are just structure changing improvement, but no really features offered.

So I approve this pull request.

**Comment by kapilag** [comment]
For a urgent bug , yes approved , but not for all the bugs fixes on Issues tab in github.

And regarding the pull request , will leave upto you guyz to decide

**Pull request merged**
